#!/usr/bin/env python3
"""
M7 CATALOG — rebuild 03_Knowledge_Mat/00_Atlas/CATALOG.md from the filed library.
Lists every skill and template by name with counts. Pure-stdlib, fast, idempotent.

Usage:  python m7_catalog.py            (auto-detects vault root)
        python m7_catalog.py --root <path>

"""
from __future__ import annotations
import argparse, sys
from datetime import datetime
from pathlib import Path

DEFAULT_ROOT = Path(__file__).resolve().parents[2] if len(Path(__file__).resolve().parents) >= 3 else Path.cwd()


def names(d: Path):
    if not d.exists():
        return []
    return sorted([p.name for p in d.iterdir() if p.is_dir() and not p.name.startswith((".", "_"))])


def main(argv=None):
    ap = argparse.ArgumentParser()
    ap.add_argument("--root", type=Path, default=DEFAULT_ROOT)
    args = ap.parse_args(argv)
    root = args.root.resolve()

    skills = names(root / "04_Tech_Lab" / "skills")
    templates = names(root / "03_Knowledge_Mat" / "00_Atlas" / "templates")
    today = f"{datetime.now():%Y-%m-%d}"

    out = [
        "---", "type: catalog", f"generated: {today}",
        "classification: M7_Command_Level_1", "---", "",
        "# M7 CATALOG — Skills & Templates", "",
        "> Auto-generated by m7_catalog.py. Single index of all vetted Claude skills",
        "> and knowledge templates in the 4-Fala Topography.", "",
        f"## Skills ({len(skills)})", "", "| # | Skill Name |", "|---|-----------|",
    ]
    for i, s in enumerate(skills, 1):
        out.append(f"| {i} | {s} |")
    out += ["", f"## Templates ({len(templates)})", "", "| # | Template Name |", "|---|--------------|"]
    for i, t in enumerate(templates, 1):
        out.append(f"| {i} | {t} |")
    out += ["", ".", "",
            "<!-- M7-FIREWALL-EXEMPT: governance-reference -->", ""]

    dest = root / "03_Knowledge_Mat" / "00_Atlas" / "CATALOG.md"
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text("\n".join(out), encoding="utf-8")
    print(f"CATALOG.md rebuilt: {len(skills)} skills, {len(templates)} templates -> {dest}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
