#!/usr/bin/env python3
"""
Shot Builder — First-time setup gate.

Walks the user through:
  1. Provider pick (fal / kie / both)
  2. API key entry + storage location
  3. Default model, resolution, aspect
  4. Output directory
  5. State directory (skill workspace path)

Writes workspace/config.json and seeds workspace/INDEX.md.

Usage:
    python setup.py                    # interactive — only runs if config.json missing
    python setup.py --reset            # wipe config and re-run gate
    python setup.py --check            # print current config and exit (non-interactive)
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

SCRIPT_DIR = Path(__file__).resolve().parent
SKILL_DIR = SCRIPT_DIR.parent
WORKSPACE = SKILL_DIR / "workspace"
CONFIG_PATH = WORKSPACE / "config.json"
INDEX_PATH = WORKSPACE / "INDEX.md"
DEFAULT_SHARED_ENV = Path.home() / ".shot-builder" / ".env"
DEFAULT_OUTPUT_DIR = Path("~/shot-builder-output")


def prompt(question: str, default: str | None = None) -> str:
    """Tiny input wrapper that surfaces the default in brackets."""
    suffix = f" [{default}]" if default else ""
    answer = input(f"{question}{suffix}: ").strip()
    return answer or (default or "")


def pick(question: str, options: list[str], default: str) -> str:
    """Numbered-choice picker. Returns the selected option string."""
    print(f"\n{question}")
    for i, opt in enumerate(options, 1):
        marker = "*" if opt == default else " "
        print(f"  {marker} {i}. {opt}")
    raw = input(f"Pick 1-{len(options)} [default {default}]: ").strip()
    if not raw:
        return default
    try:
        return options[int(raw) - 1]
    except (ValueError, IndexError):
        print(f"  → invalid pick, using default: {default}")
        return default


def write_env_key(env_path: Path, key_name: str, key_value: str) -> None:
    """Append or replace a KEY=value line in a .env file. Creates the file if missing."""
    env_path.parent.mkdir(parents=True, exist_ok=True)
    lines: list[str] = []
    if env_path.exists():
        with env_path.open("r") as f:
            lines = [line for line in f.read().splitlines() if not line.startswith(f"{key_name}=")]
    lines.append(f"{key_name}={key_value}")
    with env_path.open("w") as f:
        f.write("\n".join(lines) + "\n")
    # Lock down — keys are secrets
    env_path.chmod(0o600)


def seed_index(config: dict[str, Any]) -> None:
    """Create or refresh workspace/INDEX.md with the current config snapshot."""
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    provider = config["provider"]["primary"]
    defaults = config["defaults"]
    paths = config["paths"]
    output_dir = paths["output_dir"]
    active_project = config.get("active_project") or "—"
    workflow_mode = defaults.get("workflow_mode", "ref2video")

    content = f"""# Shot Builder — Hot Cache (INDEX.md)

<!--
============================================================
LOCKED TEMPLATE — DO NOT EDIT BY HAND.
This file is a READ-ONLY hot cache for the shot-builder skill.

DO NOT add routing logic here. Routing lives in SKILL.md.
DO NOT add reference-file restrictions here. The skill's STEP 8
  routing table is the single source of truth.
DO NOT overwrite this file. It is regenerated by setup.py and
  appended-to by fal_gen.py / kie_gen.py / prompt_only.py.
DO NOT invent new sections. The seven sections below are the
  whole template: Setup, Active project, Workflow mode, Projects,
  Rosters (cast / locations / styles), Recent renders, Notes.

If the workflow has drifted from what's documented in SKILL.md,
fix SKILL.md — never use this file as a workaround.
============================================================
-->

> Hot cache for the shot-builder skill. Auto-managed.
> Sections labeled `[auto]` are updated by scripts. Sections labeled `[manual]`
> are for the user. Agents must not edit either by hand.

**Last updated:** {now}

---

## Setup `[auto]`

| Setting | Value |
|---|---|
| Primary provider | `{provider}` |
| Fallback provider | `{config["provider"].get("fallback") or "—"}` |
| FAL key location | `{config["provider"].get("fal_key_path") or "—"}` |
| Kie key location | `{config["provider"].get("kie_key_path") or "—"}` |
| Default image model | `{defaults["image_model"]}` |
| Default image resolution | `{defaults["image_resolution"]}` |
| Default image aspect | `{defaults["image_aspect"]}` |
| Default video model | `{defaults["video_model"]}` |
| Default video resolution | `{defaults["video_resolution"]}` |
| Default video aspect | `{defaults["video_aspect"]}` |
| Default video duration | `{defaults["video_duration"]}s` |
| Workflow mode | `{workflow_mode}` |
| Output directory | `{output_dir}` |
| State directory | `{paths["state_dir"]}` |
| Default style token | `{config.get("default_style_token") or "—"}` |

---

## Active project `[auto]`

**`{active_project}`**

Renders save to `<output_dir>/<date>/{active_project}/<kind>/`. Tokens look up project-first, then global fallback.

Switch with `python scripts/project.py set <slug>` or by telling the skill "switch to <slug>". List all with `python scripts/project.py list`.

---

## Workflow mode `[auto]`

**`{workflow_mode}`**

- `ref2video` — every shot attaches a reference image (face / 3-view sheet / location plate). Prompt INCLUDES character + costume description PLUS `use attached reference for face — LIKENESS REPLICATION, do not idealize`. Identity = reference image. Wardrobe + posture + expression = prompt text.
- `text2video` — no reference image. Identity, costume, posture, expression all come from the prompt text alone. Used for synthetic characters or first-pass exploration.
- `mixed` — skill asks per-shot before composing.

To switch globally, re-run setup with `python "$SKILL_DIR/scripts/setup.py" --reset`. To override for one shot, tell the skill: "this one is text2video" or "ref2video this time".

---

## Projects `[auto]`

*No projects yet. Create one with `python scripts/project.py new "<name>"`.*

<!--
| Slug | Active | Cast | Locations | Styles |
|---|---|---|---|---|
| post-it | * | 2 | 1 | 1 |
| artlist-noise |   | 3 | 2 | 1 |
-->

---

## Cast roster — global `[auto]`

*No global cast tokens yet. Create with the character-sheet flow. Project-scoped cast lives under `workspace/projects/<slug>/cast/`.*

<!--
- `<SELF>` — one-line hook (reusable across projects)
-->

---

## Locations roster — global `[auto]`

*No global location tokens yet.*

<!--
- `<HOME-STUDIO-DAY>` — one-line hook
-->

---

## Styles roster — global `[auto]`

*No global style tokens yet. Use canned M1-M5 modes or lock a custom style with the style-sheet flow.*

<!--
- `<STYLE-WARM-CABIN>` — one-line hook (reusable across projects)
-->

**Canned modes (always available):** M1 Narrative · M2 Studio · M3 Action · M4 Performance · M5 Atmospheric — see [references/camera-grammar.md](../references/camera-grammar.md).

---

## Recent renders `[auto, append-only]`

*No renders yet.*

<!--
Per-render row format:
| Date | Provider | Model | Project | Format | Cost | Path |
|---|---|---|---|---|---|---|
| 2026-05-21 | kie | nano-banana-pro | post-it | 1x1 | $0.04 | 2026-05-21/post-it/shots/HERO_base_001.png |
-->

---

## Active gotchas / notes `[manual]`

*This is the only section the user (not the agent) should edit by hand. Add notes here when a token has a recurring issue worth remembering across sessions.*
"""
    INDEX_PATH.write_text(content)


def run_setup() -> dict[str, Any]:
    """Interactive setup gate. Returns the config dict (also writes config.json)."""
    print("=" * 60)
    print("Shot Builder — Setup")
    print("=" * 60)
    print()
    print("First-time setup. Pick a provider, paste your API key, set defaults.")
    print("You can change any of this later with `python setup.py --reset`.")
    print()

    # 1. Provider
    provider = pick(
        "Which provider?",
        ["kie", "fal", "both", "prompt_only"],
        default="kie",
    )

    fal_key_path = None
    kie_key_path = None

    # 2. API keys (skipped entirely for prompt_only)
    if provider == "prompt_only":
        print()
        print("Prompt-only mode — no API calls, no keys needed.")
        print("Renders write a .md file with the prompt to <output_dir>/<date>/<project>/prompts/.")
        print("You paste the prompt into MJ / ComfyUI / Higgsfield / Replicate / Kie UI / FAL UI yourself.")
    else:
        print()
        print("API keys — recommended location: ~/.shot-builder/.env (shared with other skills)")
        print("Alternative: workspace/.env (per-skill)")
        print()

        key_path_choice = pick(
            "Where to store API key(s)?",
            [str(DEFAULT_SHARED_ENV), str(WORKSPACE / ".env")],
            default=str(DEFAULT_SHARED_ENV),
        )
        key_path = Path(key_path_choice).expanduser()

        if provider in ("fal", "both"):
            fal_key = prompt("Paste your FAL API key (visit https://fal.ai/dashboard/keys)").strip()
            if fal_key:
                write_env_key(key_path, "FAL_KEY", fal_key)
                fal_key_path = str(key_path)
                print(f"  → saved to {key_path} (chmod 600)")
            else:
                print("  → no key entered; FAL calls will fail until you add FAL_KEY")

        if provider in ("kie", "both"):
            kie_key = prompt("Paste your Kie API key (visit https://kie.ai/api-key)").strip()
            if kie_key:
                write_env_key(key_path, "KIE_API_KEY", kie_key)
                kie_key_path = str(key_path)
                print(f"  → saved to {key_path} (chmod 600)")
            else:
                print("  → no key entered; Kie calls will fail until you add KIE_API_KEY")

    # 3. Default model
    print()
    if provider == "prompt_only":
        # No API call — model is just a label for prompt sidecars
        default_image_model = pick(
            "Default image model label (for sidecar metadata only — no API call)?",
            ["nano-banana", "nano-banana-pro", "flux-pro-ultra", "midjourney", "comfyui", "other"],
            default="nano-banana-pro",
        )
        default_video_model = pick(
            "Default video model label (for sidecar metadata only)?",
            ["seedance-pro", "kling-2.6", "veo-3.1", "runway", "sora-2", "other"],
            default="seedance-pro",
        )
    elif provider == "fal":
        default_image_model = pick(
            "Default image model?",
            [
                "fal-ai/flux-pro/v1.1-ultra",
                "fal-ai/flux-pro/v1.1",
                "fal-ai/flux/dev",
                "fal-ai/flux-pro/kontext",
                "fal-ai/recraft-v3",
            ],
            default="fal-ai/flux-pro/v1.1-ultra",
        )
        default_video_model = pick(
            "Default video model?",
            [
                "fal-ai/kling-video/v2.1/master",
                "fal-ai/kling-video/v3/pro/image-to-video",
                "fal-ai/bytedance/seedance/v1/pro/image-to-video",
                "fal-ai/veo-3",
                "fal-ai/runway-gen3/turbo/image-to-video",
            ],
            default="fal-ai/kling-video/v2.1/master",
        )
    else:
        default_image_model = pick(
            "Default image model?",
            ["nano-banana-pro", "nano-banana-basic", "flux-2", "4o-image"],
            default="nano-banana-pro",
        )
        default_video_model = pick(
            "Default video model?",
            ["kling-2.6", "veo-3.1", "runway", "sora-2"],
            default="kling-2.6",
        )

    # 4. Resolution + aspect
    default_image_resolution = pick(
        "Default image resolution?",
        ["1K", "2K", "4K"],
        default="2K",
    )
    default_image_aspect = pick(
        "Default image aspect?",
        ["2.39:1", "16:9", "4:5", "9:16", "1:1"],
        default="2.39:1",
    )
    default_video_resolution = pick(
        "Default video resolution?",
        ["720p", "1080p", "4K"],
        default="1080p",
    )
    default_video_aspect = pick(
        "Default video aspect?",
        ["16:9", "9:16", "2.39:1", "1:1"],
        default="16:9",
    )

    # 5. Workflow mode — ref2video vs text2video
    #
    # This is the SINGLE MOST IMPORTANT setting for prompt composition.
    # - ref2video: user attaches a reference image (face portrait, 3-view sheet,
    #              location plate) in every shot. The prompt INCLUDES the
    #              character description PLUS a "use attached reference for face
    #              — LIKENESS REPLICATION, do not idealize" anchor line.
    # - text2video: no reference image. Identity comes from text description
    #               alone. Used for synthetic/no-likeness characters.
    print()
    print("Workflow mode — how do you usually compose shots?")
    print("  ref2video    : you attach a character/location reference in every shot")
    print("                 (prompt includes description + LIKENESS REPLICATION anchor)")
    print("  text2video   : no reference image; identity comes from text alone")
    print("  mixed        : ask per-shot at compose time")
    workflow_mode = pick(
        "Pick a workflow mode",
        ["ref2video", "text2video", "mixed"],
        default="ref2video",
    )

    # 6. Output dir
    print()
    output_dir = prompt(
        "Output directory for generated artifacts",
        default=str(DEFAULT_OUTPUT_DIR),
    )
    Path(output_dir).mkdir(parents=True, exist_ok=True)

    # 7. Build config
    now_iso = datetime.now(timezone.utc).isoformat()
    if provider == "prompt_only":
        primary = "prompt_only"
        fallback = None
    elif provider == "both":
        primary = "kie"
        fallback = "fal"
    else:
        primary = provider
        fallback = None

    config: dict[str, Any] = {
        "version": "1.1",
        "created": now_iso,
        "modified": now_iso,
        "provider": {
            "primary": primary,
            "fallback": fallback,
            "fal_key_path": fal_key_path,
            "kie_key_path": kie_key_path,
        },
        "defaults": {
            "image_model": default_image_model,
            "image_resolution": default_image_resolution,
            "image_aspect": default_image_aspect,
            "video_model": default_video_model,
            "video_resolution": default_video_resolution,
            "video_aspect": default_video_aspect,
            "video_duration": 5,
            "frame_rate": "24fps_180shutter",
            "workflow_mode": workflow_mode,
        },
        "paths": {
            "output_dir": output_dir,
            "state_dir": str(WORKSPACE),
        },
        "active_project": None,
        "default_style_token": None,
    }

    WORKSPACE.mkdir(parents=True, exist_ok=True)
    CONFIG_PATH.write_text(json.dumps(config, indent=2))
    seed_index(config)

    print()
    print("=" * 60)
    print("Setup complete.")
    print(f"  Config: {CONFIG_PATH}")
    print(f"  Index:  {INDEX_PATH}")
    print(f"  Output: {output_dir}")
    print("=" * 60)
    return config


def load_config() -> dict[str, Any] | None:
    if not CONFIG_PATH.exists():
        return None
    return json.loads(CONFIG_PATH.read_text())


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--reset", action="store_true", help="Wipe config and re-run setup")
    ap.add_argument("--check", action="store_true", help="Print current config and exit")
    args = ap.parse_args()

    if args.check:
        cfg = load_config()
        if cfg is None:
            print("No config.json yet. Run `python setup.py` to set up.", file=sys.stderr)
            return 1
        print(json.dumps(cfg, indent=2))
        return 0

    if args.reset and CONFIG_PATH.exists():
        CONFIG_PATH.unlink()
        print(f"Removed {CONFIG_PATH}. Re-running setup...")
        print()

    existing = load_config()
    if existing is not None and not args.reset:
        print(f"Config already exists at {CONFIG_PATH}.")
        print("Use `python setup.py --reset` to re-run setup, or `--check` to view current config.")
        return 0

    run_setup()
    return 0


if __name__ == "__main__":
    sys.exit(main())
